### ISSUE TITLE
Misprint in a comment

### ISSUE THREAD

**Issue by IosifGuzeev** [unitedtimur/server_client_chat#1]
https://github.com/unitedtimur/server_client_chat/blob/cabe1a13b12eec31857035b03ce40d75e5d61756/client/client.cpp#L83

**Comment by unitedtimur** [comment]
Как должно быть?)

**Comment by IosifGuzeev** [comment]
// Инициализация аналогичн**а** серверу

**Comment by IosifGuzeev** [comment]
Извините, автор issue  ещё не проснулся
